### PR TITLE
Resubmission by Adithya Parupudi - About me, challenge 1 and 2

### PR DESCRIPTION
**Pull request by Adithya1243**

### CODE REVIEW

**Review by ThogaruSathvik — CHANGES_REQUESTED** [review]
Hi Adithya, I am not sure about this, but did you sink your github repo with the Dacss  template branch.
I see the MaxRolfe.qmd file in the about folder. It should not be there in your github project repo
Let me know if you have any issues and book an appointment

**Comment by Adithya1243** [comment]
I pasted the whole folder when Meredith asked us to and looks like MaxRolfe's files also ended up here. 
In the previous repo, it was okay to have our file + maxrolfe's files. I thought it would be the same here.. so i didnt remove them.

Since the pull request is still open, i will remove MaxRolfe's files, and commit again.

**Comment by Adithya1243** [comment]
Please check it now. I've removed MaxRolfe's files and change the title of my pull request as well

**Review by ThogaruSathvik — APPROVED** [review]
Thank you Adithya. 
We are sort of in process of helping you create your own blog which has only your posts and details . So want to make sure there are no unnecessary files in your repo.

**Pull request merged**
